[theme]
primaryColor = "#087f72"
backgroundColor = "#f6f8fb"
secondaryBackgroundColor = "#ffffff"
textColor = "#182b3a"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
